server:
  port: 8080

spring:
  application:
    name: tg-bot-finance-tracker-002
  main:
    web-application-type: none
#  datasource:
#    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
#    username: ${POSTGRES_USERNAME:postgres}
#    password: ${POSTGRES_PASSWORD:postgres}
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 10
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate.default_schema: ${POSTGRES_SCHEMA:pins}
#  liquibase:
#    default-schema: ${POSTGRES_SCHEMA:pins}
#    change-log: classpath:/${POSTGRES_SCHEMA:pins}/master.yml

bot:
  name: "tg_base_001_bot"
  token: ${BOT_TOKEN_001:8382992581:AAHcjAMVR6uO9uAMhJ39wJAfS87kIwNsuFA}


google:
  sheets:
    spreadsheet-id: 1IxHnCSnKQSpTsZjCrlGX-9DguSqyhFPy9w2HjkRhY6o
